name: Flutter_Analyzer

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - name: Run dart format
        run: dart format --set-exit-if-changed .
      - name: flutter analyze
        run: flutter analyze
